#
# Copyright (c) 2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Build che-code-dev image

# Trigger the workflow on pull request
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - devfile.yaml
      - '.che/*'
      - '.rebase/*'

env:
  LOCAL_TEST_DIR: /tmp
jobs:
  build-che-code-dev:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout che-code source code
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Che-Code Docker image
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "Pull request $PR_NUMBER"

          DEV_IMAGE_NAME=quay.io/che-incubator-pull-requests/che-code-dev:pr-${PR_NUMBER}-dev-amd64
          echo "Dev image $DEV_IMAGE_NAME"

          # docker buildx build --platform linux/amd64 --progress=plain --push -f build/dockerfiles/dev.Dockerfile -t ${DEV_IMAGE_NAME} .
          docker buildx build --platform linux/amd64 --progress=plain -f build/dockerfiles/dev.Dockerfile -t ${DEV_IMAGE_NAME} .

      - name: Display docker images
        run: |
          docker images
