#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Pull Request Check

# Trigger the workflow on pull request
on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout che-code source code
        uses: actions/checkout@v4

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: che-code
          path: che-code.tgz

      - name: Store PR info
        run: |
          echo "${{ github.event.number }}" > PR_NUMBER
          echo "${{ github.event.pull_request.head.sha }}" > PR_SHA

      - name: Upload PR Number artifact
        uses: actions/upload-artifact@v4
        with:
          name: pull-request-number
          path: PR_NUMBER

      - name: Upload PR SHA artifact
        uses: actions/upload-artifact@v4
        with:
          name: pull-request-sha
          path: PR_SHA
