#
# Copyright (c) 2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Smoke Test

# Trigger the workflow on pull request
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - devfile.yaml
      - '.che/*'
      - '.rebase/*'

jobs:
  smoke-test:

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     dist: [ 'alpine', 'ubi8' ]
    #     chectlchannel: [ 'next', 'stable' ]
    #   matrix:
    #     dist: [ 'alpine' ]
    #     chectlchannel: [ 'stable' ]

    # env:
    #   JOB_NAME_SUFFIX: ${{matrix.dist}} ${{matrix.chectlchannel}}

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout che-code source code
        uses: actions/checkout@v2

      # - name: Checkout source code
      #   uses: actions/checkout@v3

      - name: Configuring nodejs 14.x version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Start minikube
        id: run-minikube
        uses: che-incubator/setup-minikube-action@next
        with:
          minikube-version: v1.23.2

      - name: Install yq
        run: sudo pip install yq

      # - name: Build
      #   run: |
      #     echo "-------------------------------------------------------------------------------"
      #     echo "> {{matrix.dist}}: ${{matrix.dist}}"
      #     echo "> {{matrix.chectlchannel}}: ${{matrix.chectlchannel}}"
      #     echo "-------------------------------------------------------------------------------"
      #     docker image prune -a -f
      #     docker build -f build/dockerfiles/linux-libc.Dockerfile -t linux-libc-amd64 .

      - name: Install chectl
        run: bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next

      - name: Run tests
        run: /bin/bash build/scripts/minikube-tests/run-tests.sh

      # - name: Deploy Eclipse Che
      #   id: deploy-che
      #   uses: che-incubator/che-deploy-action@next
      #   with:
      #     chectl-channel: ${{matrix.chectlchannel}}

      # - name: Run Happy Path tests
      #   id: run-happy-path-tests
      #   uses: che-incubator/happy-path-tests-action@next
      #   with:
      #     che-url: ${{ steps.deploy-che.outputs.che-url }}
      #     devfile-url: ${{ steps.devfile-che-theia.outputs.devfile-url }}
      #     e2e-version: ${{matrix.chectlchannel}}
