#
# Copyright (c) 2022 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: Try in Web IDE

on:
  pull_request_target:
    types: opened

jobs:
  add-link:
    runs-on: ubuntu-22.04
    steps:
      - name: Add DevSandbox link
        uses: redhat-actions/try-in-web-ide@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_comment: true
          add_status: false
      - name: Add Dogfooding link
        uses: redhat-actions/try-in-web-ide@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_comment: true
          add_status: false
          web_ide_instance: https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com
          comment_badge: https://img.shields.io/static/v1?label=Eclipse%20Che%20(nightly)&message=Dev%20cluster%20(for%20maintainers)&logo=eclipseche&color=525C86&labelColor=FDB940
